- name: "Create 'tiny' flavor with 1024MB of RAM, 1 virtual CPU, and 10GB of local disk, and 10GB of ephemeral."
  os_nova_flavor:
    cloud: ospcloud
    state: present
    name: m2.small
    ram: 2048
    vcpus: 1
    disk: 10
